name: JumpCutter2

on:
  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup FFmpeg
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install zip unzip
          sudo apt-get install tree
          sudo apt install ffmpeg
          ffmpeg -version
          
      - name: Prepare
        run: |
          sudo pip3 install pyinstaller
          wget https://github.com/deezer/spleeter/archive/refs/tags/v2.3.0.zip
          mkdir -p JumpCutter2/pretrained_models/5stem
          unzip -d JumpCutter2/pretrained_models/5stems v2.3.0.zip 

      - name: Build
        run: |
          pyinstaller -F JumpCutter2/__main__.py
          ls -lh dist/

